// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: static_data_proto.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace com.bsl.data {

  /// <summary>Holder for reflection information generated from static_data_proto.proto</summary>
  public static partial class StaticDataProtoReflection {

    #region Descriptor
    /// <summary>File descriptor for static_data_proto.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StaticDataProtoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdzdGF0aWNfZGF0YV9wcm90by5wcm90byLzDQoLRGF0YU1hbmFnZXISTAoY",
            "Y3JhenlQYWlqaXVDYXJkR3JvdXBEYXRhGAEgAygLMiouRGF0YU1hbmFnZXIu",
            "Q3JhenlQYWlqaXVDYXJkR3JvdXBEYXRhRW50cnkSVgodY3JhenlQYWlqaXVD",
            "YXJkR3JvdXBTY29yZURhdGEYAiADKAsyLy5EYXRhTWFuYWdlci5DcmF6eVBh",
            "aWppdUNhcmRHcm91cFNjb3JlRGF0YUVudHJ5Ek4KGWxhb3RpZVBhaWppdUNh",
            "cmRHcm91cERhdGEYAyADKAsyKy5EYXRhTWFuYWdlci5MYW90aWVQYWlqaXVD",
            "YXJkR3JvdXBEYXRhRW50cnkSWAoebGFvdGllUGFpaml1Q2FyZEdyb3VwU2Nv",
            "cmVEYXRhGAQgAygLMjAuRGF0YU1hbmFnZXIuTGFvdGllUGFpaml1Q2FyZEdy",
            "b3VwU2NvcmVEYXRhRW50cnkSOAoOcGFpaml1Q2FyZERhdGEYBSADKAsyIC5E",
            "YXRhTWFuYWdlci5QYWlqaXVDYXJkRGF0YUVudHJ5EkIKE3BhaWppdUNhcmRH",
            "cm91cERhdGEYBiADKAsyJS5EYXRhTWFuYWdlci5QYWlqaXVDYXJkR3JvdXBE",
            "YXRhRW50cnkSTAoYcGFpaml1Q2FyZEdyb3VwU2NvcmVEYXRhGAcgAygLMiou",
            "RGF0YU1hbmFnZXIuUGFpaml1Q2FyZEdyb3VwU2NvcmVEYXRhRW50cnkSLAoI",
            "cm9vbURhdGEYCCADKAsyGi5EYXRhTWFuYWdlci5Sb29tRGF0YUVudHJ5EiwK",
            "CHRlc3REYXRhGAkgAygLMhouRGF0YU1hbmFnZXIuVGVzdERhdGFFbnRyeRJQ",
            "Chp4aWFveWFvUGFpaml1Q2FyZEdyb3VwRGF0YRgKIAMoCzIsLkRhdGFNYW5h",
            "Z2VyLlhpYW95YW9QYWlqaXVDYXJkR3JvdXBEYXRhRW50cnkSWgofeGlhb3lh",
            "b1BhaWppdUNhcmRHcm91cFNjb3JlRGF0YRgLIAMoCzIxLkRhdGFNYW5hZ2Vy",
            "LlhpYW95YW9QYWlqaXVDYXJkR3JvdXBTY29yZURhdGFFbnRyeRpaCh1DcmF6",
            "eVBhaWppdUNhcmRHcm91cERhdGFFbnRyeRILCgNrZXkYASABKAkSKAoFdmFs",
            "dWUYAiABKAsyGS5DcmF6eVBhaWppdUNhcmRHcm91cERhdGE6AjgBGmQKIkNy",
            "YXp5UGFpaml1Q2FyZEdyb3VwU2NvcmVEYXRhRW50cnkSCwoDa2V5GAEgASgJ",
            "Ei0KBXZhbHVlGAIgASgLMh4uQ3JhenlQYWlqaXVDYXJkR3JvdXBTY29yZURh",
            "dGE6AjgBGlwKHkxhb3RpZVBhaWppdUNhcmRHcm91cERhdGFFbnRyeRILCgNr",
            "ZXkYASABKAkSKQoFdmFsdWUYAiABKAsyGi5MYW90aWVQYWlqaXVDYXJkR3Jv",
            "dXBEYXRhOgI4ARpmCiNMYW90aWVQYWlqaXVDYXJkR3JvdXBTY29yZURhdGFF",
            "bnRyeRILCgNrZXkYASABKAkSLgoFdmFsdWUYAiABKAsyHy5MYW90aWVQYWlq",
            "aXVDYXJkR3JvdXBTY29yZURhdGE6AjgBGkYKE1BhaWppdUNhcmREYXRhRW50",
            "cnkSCwoDa2V5GAEgASgFEh4KBXZhbHVlGAIgASgLMg8uUGFpaml1Q2FyZERh",
            "dGE6AjgBGlAKGFBhaWppdUNhcmRHcm91cERhdGFFbnRyeRILCgNrZXkYASAB",
            "KAkSIwoFdmFsdWUYAiABKAsyFC5QYWlqaXVDYXJkR3JvdXBEYXRhOgI4ARpa",
            "Ch1QYWlqaXVDYXJkR3JvdXBTY29yZURhdGFFbnRyeRILCgNrZXkYASABKAkS",
            "KAoFdmFsdWUYAiABKAsyGS5QYWlqaXVDYXJkR3JvdXBTY29yZURhdGE6AjgB",
            "GjoKDVJvb21EYXRhRW50cnkSCwoDa2V5GAEgASgJEhgKBXZhbHVlGAIgASgL",
            "MgkuUm9vbURhdGE6AjgBGjoKDVRlc3REYXRhRW50cnkSCwoDa2V5GAEgASgF",
            "EhgKBXZhbHVlGAIgASgLMgkuVGVzdERhdGE6AjgBGl4KH1hpYW95YW9QYWlq",
            "aXVDYXJkR3JvdXBEYXRhRW50cnkSCwoDa2V5GAEgASgJEioKBXZhbHVlGAIg",
            "ASgLMhsuWGlhb3lhb1BhaWppdUNhcmRHcm91cERhdGE6AjgBGmgKJFhpYW95",
            "YW9QYWlqaXVDYXJkR3JvdXBTY29yZURhdGFFbnRyeRILCgNrZXkYASABKAkS",
            "LwoFdmFsdWUYAiABKAsyIC5YaWFveWFvUGFpaml1Q2FyZEdyb3VwU2NvcmVE",
            "YXRhOgI4ASI0ChhDcmF6eVBhaWppdUNhcmRHcm91cERhdGESCgoCaWQYASAB",
            "KAkSDAoEbmFtZRgCIAEoCSI6Ch1DcmF6eVBhaWppdUNhcmRHcm91cFNjb3Jl",
            "RGF0YRIKCgJpZBgBIAEoCRINCgVzY29yZRgCIAEoBSI1ChlMYW90aWVQYWlq",
            "aXVDYXJkR3JvdXBEYXRhEgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAkiOwoe",
            "TGFvdGllUGFpaml1Q2FyZEdyb3VwU2NvcmVEYXRhEgoKAmlkGAEgASgJEg0K",
            "BXNjb3JlGAIgASgFIioKDlBhaWppdUNhcmREYXRhEgoKAmlkGAEgASgFEgwK",
            "BGNhcmQYAiABKAUiLwoTUGFpaml1Q2FyZEdyb3VwRGF0YRIKCgJpZBgBIAEo",
            "CRIMCgRuYW1lGAIgASgJIjUKGFBhaWppdUNhcmRHcm91cFNjb3JlRGF0YRIK",
            "CgJpZBgBIAEoCRINCgVzY29yZRgCIAEoBSL5AwoIUm9vbURhdGESCgoCaWQY",
            "ASABKAkSIwoFbW9uZXkYAiADKAsyFC5Sb29tRGF0YS5Nb25leUVudHJ5Eg4K",
            "Bm1heEJldBgDIAEoARIrCgllYWNoTW9uZXkYBCADKAsyGC5Sb29tRGF0YS5F",
            "YWNoTW9uZXlFbnRyeRIRCglpc0FkZEdvbGQYBSABKAUSFgoOaXNXaW5uZXIy",
            "RGl6aHUYBiABKAUSFgoOcGFpaml1RGF0YU5hbWUYByABKAkSKwoJZW50ZXJH",
            "b2xkGAggAygLMhguUm9vbURhdGEuRW50ZXJHb2xkRW50cnkSJwoHb3V0R29s",
            "ZBgJIAMoCzIWLlJvb21EYXRhLk91dEdvbGRFbnRyeRIOCgZyZWJhdGUYCiAB",
            "KAUSFAoMaW5zdGFuY2VOYW1lGAsgASgJGiwKCk1vbmV5RW50cnkSCwoDa2V5",
            "GAEgASgFEg0KBXZhbHVlGAIgASgFOgI4ARowCg5FYWNoTW9uZXlFbnRyeRIL",
            "CgNrZXkYASABKAUSDQoFdmFsdWUYAiABKAU6AjgBGjAKDkVudGVyR29sZEVu",
            "dHJ5EgsKA2tleRgBIAEoBRINCgV2YWx1ZRgCIAEoBToCOAEaLgoMT3V0R29s",
            "ZEVudHJ5EgsKA2tleRgBIAEoBRINCgV2YWx1ZRgCIAEoBToCOAEivQIKCFRl",
            "c3REYXRhEgoKAmlkGAEgASgFEgwKBG5hbWUYAiABKAkSCwoDYWdlGAMgASgF",
            "EgsKA2V4cBgEIAMoBRIlCgZ3ZWFwb24YBSADKAsyFS5UZXN0RGF0YS5XZWFw",
            "b25FbnRyeRIQCgh0ZXN0TG9uZxgGIAEoAxISCgp0ZXN0RG91YmxlGAcgASgB",
            "EhYKDnRlc3RMaXN0RG91YmxlGAggAygBEjMKDXRlc3RNYXBEb3VibGUYCSAD",
            "KAsyHC5UZXN0RGF0YS5UZXN0TWFwRG91YmxlRW50cnkaLQoLV2VhcG9uRW50",
            "cnkSCwoDa2V5GAEgASgFEg0KBXZhbHVlGAIgASgJOgI4ARo0ChJUZXN0TWFw",
            "RG91YmxlRW50cnkSCwoDa2V5GAEgASgDEg0KBXZhbHVlGAIgASgBOgI4ASI2",
            "ChpYaWFveWFvUGFpaml1Q2FyZEdyb3VwRGF0YRIKCgJpZBgBIAEoCRIMCgRu",
            "YW1lGAIgASgJIjwKH1hpYW95YW9QYWlqaXVDYXJkR3JvdXBTY29yZURhdGES",
            "CgoCaWQYASABKAkSDQoFc2NvcmUYAiABKAVCPwodY29tLmNvZGUuc2VydmVy",
            "LmNvbnN0YW50LmRhdGFCD1N0YXRpY0RhdGFQcm90b6oCDGNvbS5ic2wuZGF0",
            "YWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::com.bsl.data.DataManager), global::com.bsl.data.DataManager.Parser, new[]{ "CrazyPaijiuCardGroupData", "CrazyPaijiuCardGroupScoreData", "LaotiePaijiuCardGroupData", "LaotiePaijiuCardGroupScoreData", "PaijiuCardData", "PaijiuCardGroupData", "PaijiuCardGroupScoreData", "RoomData", "TestData", "XiaoyaoPaijiuCardGroupData", "XiaoyaoPaijiuCardGroupScoreData" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, null, null, null, null, null, null, null, null, null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::com.bsl.data.CrazyPaijiuCardGroupData), global::com.bsl.data.CrazyPaijiuCardGroupData.Parser, new[]{ "Id", "Name" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::com.bsl.data.CrazyPaijiuCardGroupScoreData), global::com.bsl.data.CrazyPaijiuCardGroupScoreData.Parser, new[]{ "Id", "Score" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::com.bsl.data.LaotiePaijiuCardGroupData), global::com.bsl.data.LaotiePaijiuCardGroupData.Parser, new[]{ "Id", "Name" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::com.bsl.data.LaotiePaijiuCardGroupScoreData), global::com.bsl.data.LaotiePaijiuCardGroupScoreData.Parser, new[]{ "Id", "Score" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::com.bsl.data.PaijiuCardData), global::com.bsl.data.PaijiuCardData.Parser, new[]{ "Id", "Card" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::com.bsl.data.PaijiuCardGroupData), global::com.bsl.data.PaijiuCardGroupData.Parser, new[]{ "Id", "Name" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::com.bsl.data.PaijiuCardGroupScoreData), global::com.bsl.data.PaijiuCardGroupScoreData.Parser, new[]{ "Id", "Score" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::com.bsl.data.RoomData), global::com.bsl.data.RoomData.Parser, new[]{ "Id", "Money", "MaxBet", "EachMoney", "IsAddGold", "IsWinner2Dizhu", "PaijiuDataName", "EnterGold", "OutGold", "Rebate", "InstanceName" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, null, null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::com.bsl.data.TestData), global::com.bsl.data.TestData.Parser, new[]{ "Id", "Name", "Age", "Exp", "Weapon", "TestLong", "TestDouble", "TestListDouble", "TestMapDouble" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::com.bsl.data.XiaoyaoPaijiuCardGroupData), global::com.bsl.data.XiaoyaoPaijiuCardGroupData.Parser, new[]{ "Id", "Name" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::com.bsl.data.XiaoyaoPaijiuCardGroupScoreData), global::com.bsl.data.XiaoyaoPaijiuCardGroupScoreData.Parser, new[]{ "Id", "Score" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class DataManager : pb::IMessage<DataManager> {
    private static readonly pb::MessageParser<DataManager> _parser = new pb::MessageParser<DataManager>(() => new DataManager());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DataManager> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::com.bsl.data.StaticDataProtoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DataManager() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DataManager(DataManager other) : this() {
      crazyPaijiuCardGroupData_ = other.crazyPaijiuCardGroupData_.Clone();
      crazyPaijiuCardGroupScoreData_ = other.crazyPaijiuCardGroupScoreData_.Clone();
      laotiePaijiuCardGroupData_ = other.laotiePaijiuCardGroupData_.Clone();
      laotiePaijiuCardGroupScoreData_ = other.laotiePaijiuCardGroupScoreData_.Clone();
      paijiuCardData_ = other.paijiuCardData_.Clone();
      paijiuCardGroupData_ = other.paijiuCardGroupData_.Clone();
      paijiuCardGroupScoreData_ = other.paijiuCardGroupScoreData_.Clone();
      roomData_ = other.roomData_.Clone();
      testData_ = other.testData_.Clone();
      xiaoyaoPaijiuCardGroupData_ = other.xiaoyaoPaijiuCardGroupData_.Clone();
      xiaoyaoPaijiuCardGroupScoreData_ = other.xiaoyaoPaijiuCardGroupScoreData_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DataManager Clone() {
      return new DataManager(this);
    }

    /// <summary>Field number for the "crazyPaijiuCardGroupData" field.</summary>
    public const int CrazyPaijiuCardGroupDataFieldNumber = 1;
    private static readonly pbc::MapField<string, global::com.bsl.data.CrazyPaijiuCardGroupData>.Codec _map_crazyPaijiuCardGroupData_codec
        = new pbc::MapField<string, global::com.bsl.data.CrazyPaijiuCardGroupData>.Codec(pb::FieldCodec.ForString(10), pb::FieldCodec.ForMessage(18, global::com.bsl.data.CrazyPaijiuCardGroupData.Parser), 10);
    private readonly pbc::MapField<string, global::com.bsl.data.CrazyPaijiuCardGroupData> crazyPaijiuCardGroupData_ = new pbc::MapField<string, global::com.bsl.data.CrazyPaijiuCardGroupData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::com.bsl.data.CrazyPaijiuCardGroupData> CrazyPaijiuCardGroupData {
      get { return crazyPaijiuCardGroupData_; }
    }

    /// <summary>Field number for the "crazyPaijiuCardGroupScoreData" field.</summary>
    public const int CrazyPaijiuCardGroupScoreDataFieldNumber = 2;
    private static readonly pbc::MapField<string, global::com.bsl.data.CrazyPaijiuCardGroupScoreData>.Codec _map_crazyPaijiuCardGroupScoreData_codec
        = new pbc::MapField<string, global::com.bsl.data.CrazyPaijiuCardGroupScoreData>.Codec(pb::FieldCodec.ForString(10), pb::FieldCodec.ForMessage(18, global::com.bsl.data.CrazyPaijiuCardGroupScoreData.Parser), 18);
    private readonly pbc::MapField<string, global::com.bsl.data.CrazyPaijiuCardGroupScoreData> crazyPaijiuCardGroupScoreData_ = new pbc::MapField<string, global::com.bsl.data.CrazyPaijiuCardGroupScoreData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::com.bsl.data.CrazyPaijiuCardGroupScoreData> CrazyPaijiuCardGroupScoreData {
      get { return crazyPaijiuCardGroupScoreData_; }
    }

    /// <summary>Field number for the "laotiePaijiuCardGroupData" field.</summary>
    public const int LaotiePaijiuCardGroupDataFieldNumber = 3;
    private static readonly pbc::MapField<string, global::com.bsl.data.LaotiePaijiuCardGroupData>.Codec _map_laotiePaijiuCardGroupData_codec
        = new pbc::MapField<string, global::com.bsl.data.LaotiePaijiuCardGroupData>.Codec(pb::FieldCodec.ForString(10), pb::FieldCodec.ForMessage(18, global::com.bsl.data.LaotiePaijiuCardGroupData.Parser), 26);
    private readonly pbc::MapField<string, global::com.bsl.data.LaotiePaijiuCardGroupData> laotiePaijiuCardGroupData_ = new pbc::MapField<string, global::com.bsl.data.LaotiePaijiuCardGroupData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::com.bsl.data.LaotiePaijiuCardGroupData> LaotiePaijiuCardGroupData {
      get { return laotiePaijiuCardGroupData_; }
    }

    /// <summary>Field number for the "laotiePaijiuCardGroupScoreData" field.</summary>
    public const int LaotiePaijiuCardGroupScoreDataFieldNumber = 4;
    private static readonly pbc::MapField<string, global::com.bsl.data.LaotiePaijiuCardGroupScoreData>.Codec _map_laotiePaijiuCardGroupScoreData_codec
        = new pbc::MapField<string, global::com.bsl.data.LaotiePaijiuCardGroupScoreData>.Codec(pb::FieldCodec.ForString(10), pb::FieldCodec.ForMessage(18, global::com.bsl.data.LaotiePaijiuCardGroupScoreData.Parser), 34);
    private readonly pbc::MapField<string, global::com.bsl.data.LaotiePaijiuCardGroupScoreData> laotiePaijiuCardGroupScoreData_ = new pbc::MapField<string, global::com.bsl.data.LaotiePaijiuCardGroupScoreData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::com.bsl.data.LaotiePaijiuCardGroupScoreData> LaotiePaijiuCardGroupScoreData {
      get { return laotiePaijiuCardGroupScoreData_; }
    }

    /// <summary>Field number for the "paijiuCardData" field.</summary>
    public const int PaijiuCardDataFieldNumber = 5;
    private static readonly pbc::MapField<int, global::com.bsl.data.PaijiuCardData>.Codec _map_paijiuCardData_codec
        = new pbc::MapField<int, global::com.bsl.data.PaijiuCardData>.Codec(pb::FieldCodec.ForInt32(8), pb::FieldCodec.ForMessage(18, global::com.bsl.data.PaijiuCardData.Parser), 42);
    private readonly pbc::MapField<int, global::com.bsl.data.PaijiuCardData> paijiuCardData_ = new pbc::MapField<int, global::com.bsl.data.PaijiuCardData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, global::com.bsl.data.PaijiuCardData> PaijiuCardData {
      get { return paijiuCardData_; }
    }

    /// <summary>Field number for the "paijiuCardGroupData" field.</summary>
    public const int PaijiuCardGroupDataFieldNumber = 6;
    private static readonly pbc::MapField<string, global::com.bsl.data.PaijiuCardGroupData>.Codec _map_paijiuCardGroupData_codec
        = new pbc::MapField<string, global::com.bsl.data.PaijiuCardGroupData>.Codec(pb::FieldCodec.ForString(10), pb::FieldCodec.ForMessage(18, global::com.bsl.data.PaijiuCardGroupData.Parser), 50);
    private readonly pbc::MapField<string, global::com.bsl.data.PaijiuCardGroupData> paijiuCardGroupData_ = new pbc::MapField<string, global::com.bsl.data.PaijiuCardGroupData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::com.bsl.data.PaijiuCardGroupData> PaijiuCardGroupData {
      get { return paijiuCardGroupData_; }
    }

    /// <summary>Field number for the "paijiuCardGroupScoreData" field.</summary>
    public const int PaijiuCardGroupScoreDataFieldNumber = 7;
    private static readonly pbc::MapField<string, global::com.bsl.data.PaijiuCardGroupScoreData>.Codec _map_paijiuCardGroupScoreData_codec
        = new pbc::MapField<string, global::com.bsl.data.PaijiuCardGroupScoreData>.Codec(pb::FieldCodec.ForString(10), pb::FieldCodec.ForMessage(18, global::com.bsl.data.PaijiuCardGroupScoreData.Parser), 58);
    private readonly pbc::MapField<string, global::com.bsl.data.PaijiuCardGroupScoreData> paijiuCardGroupScoreData_ = new pbc::MapField<string, global::com.bsl.data.PaijiuCardGroupScoreData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::com.bsl.data.PaijiuCardGroupScoreData> PaijiuCardGroupScoreData {
      get { return paijiuCardGroupScoreData_; }
    }

    /// <summary>Field number for the "roomData" field.</summary>
    public const int RoomDataFieldNumber = 8;
    private static readonly pbc::MapField<string, global::com.bsl.data.RoomData>.Codec _map_roomData_codec
        = new pbc::MapField<string, global::com.bsl.data.RoomData>.Codec(pb::FieldCodec.ForString(10), pb::FieldCodec.ForMessage(18, global::com.bsl.data.RoomData.Parser), 66);
    private readonly pbc::MapField<string, global::com.bsl.data.RoomData> roomData_ = new pbc::MapField<string, global::com.bsl.data.RoomData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::com.bsl.data.RoomData> RoomData {
      get { return roomData_; }
    }

    /// <summary>Field number for the "testData" field.</summary>
    public const int TestDataFieldNumber = 9;
    private static readonly pbc::MapField<int, global::com.bsl.data.TestData>.Codec _map_testData_codec
        = new pbc::MapField<int, global::com.bsl.data.TestData>.Codec(pb::FieldCodec.ForInt32(8), pb::FieldCodec.ForMessage(18, global::com.bsl.data.TestData.Parser), 74);
    private readonly pbc::MapField<int, global::com.bsl.data.TestData> testData_ = new pbc::MapField<int, global::com.bsl.data.TestData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, global::com.bsl.data.TestData> TestData {
      get { return testData_; }
    }

    /// <summary>Field number for the "xiaoyaoPaijiuCardGroupData" field.</summary>
    public const int XiaoyaoPaijiuCardGroupDataFieldNumber = 10;
    private static readonly pbc::MapField<string, global::com.bsl.data.XiaoyaoPaijiuCardGroupData>.Codec _map_xiaoyaoPaijiuCardGroupData_codec
        = new pbc::MapField<string, global::com.bsl.data.XiaoyaoPaijiuCardGroupData>.Codec(pb::FieldCodec.ForString(10), pb::FieldCodec.ForMessage(18, global::com.bsl.data.XiaoyaoPaijiuCardGroupData.Parser), 82);
    private readonly pbc::MapField<string, global::com.bsl.data.XiaoyaoPaijiuCardGroupData> xiaoyaoPaijiuCardGroupData_ = new pbc::MapField<string, global::com.bsl.data.XiaoyaoPaijiuCardGroupData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::com.bsl.data.XiaoyaoPaijiuCardGroupData> XiaoyaoPaijiuCardGroupData {
      get { return xiaoyaoPaijiuCardGroupData_; }
    }

    /// <summary>Field number for the "xiaoyaoPaijiuCardGroupScoreData" field.</summary>
    public const int XiaoyaoPaijiuCardGroupScoreDataFieldNumber = 11;
    private static readonly pbc::MapField<string, global::com.bsl.data.XiaoyaoPaijiuCardGroupScoreData>.Codec _map_xiaoyaoPaijiuCardGroupScoreData_codec
        = new pbc::MapField<string, global::com.bsl.data.XiaoyaoPaijiuCardGroupScoreData>.Codec(pb::FieldCodec.ForString(10), pb::FieldCodec.ForMessage(18, global::com.bsl.data.XiaoyaoPaijiuCardGroupScoreData.Parser), 90);
    private readonly pbc::MapField<string, global::com.bsl.data.XiaoyaoPaijiuCardGroupScoreData> xiaoyaoPaijiuCardGroupScoreData_ = new pbc::MapField<string, global::com.bsl.data.XiaoyaoPaijiuCardGroupScoreData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::com.bsl.data.XiaoyaoPaijiuCardGroupScoreData> XiaoyaoPaijiuCardGroupScoreData {
      get { return xiaoyaoPaijiuCardGroupScoreData_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DataManager);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DataManager other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!CrazyPaijiuCardGroupData.Equals(other.CrazyPaijiuCardGroupData)) return false;
      if (!CrazyPaijiuCardGroupScoreData.Equals(other.CrazyPaijiuCardGroupScoreData)) return false;
      if (!LaotiePaijiuCardGroupData.Equals(other.LaotiePaijiuCardGroupData)) return false;
      if (!LaotiePaijiuCardGroupScoreData.Equals(other.LaotiePaijiuCardGroupScoreData)) return false;
      if (!PaijiuCardData.Equals(other.PaijiuCardData)) return false;
      if (!PaijiuCardGroupData.Equals(other.PaijiuCardGroupData)) return false;
      if (!PaijiuCardGroupScoreData.Equals(other.PaijiuCardGroupScoreData)) return false;
      if (!RoomData.Equals(other.RoomData)) return false;
      if (!TestData.Equals(other.TestData)) return false;
      if (!XiaoyaoPaijiuCardGroupData.Equals(other.XiaoyaoPaijiuCardGroupData)) return false;
      if (!XiaoyaoPaijiuCardGroupScoreData.Equals(other.XiaoyaoPaijiuCardGroupScoreData)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= CrazyPaijiuCardGroupData.GetHashCode();
      hash ^= CrazyPaijiuCardGroupScoreData.GetHashCode();
      hash ^= LaotiePaijiuCardGroupData.GetHashCode();
      hash ^= LaotiePaijiuCardGroupScoreData.GetHashCode();
      hash ^= PaijiuCardData.GetHashCode();
      hash ^= PaijiuCardGroupData.GetHashCode();
      hash ^= PaijiuCardGroupScoreData.GetHashCode();
      hash ^= RoomData.GetHashCode();
      hash ^= TestData.GetHashCode();
      hash ^= XiaoyaoPaijiuCardGroupData.GetHashCode();
      hash ^= XiaoyaoPaijiuCardGroupScoreData.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      crazyPaijiuCardGroupData_.WriteTo(output, _map_crazyPaijiuCardGroupData_codec);
      crazyPaijiuCardGroupScoreData_.WriteTo(output, _map_crazyPaijiuCardGroupScoreData_codec);
      laotiePaijiuCardGroupData_.WriteTo(output, _map_laotiePaijiuCardGroupData_codec);
      laotiePaijiuCardGroupScoreData_.WriteTo(output, _map_laotiePaijiuCardGroupScoreData_codec);
      paijiuCardData_.WriteTo(output, _map_paijiuCardData_codec);
      paijiuCardGroupData_.WriteTo(output, _map_paijiuCardGroupData_codec);
      paijiuCardGroupScoreData_.WriteTo(output, _map_paijiuCardGroupScoreData_codec);
      roomData_.WriteTo(output, _map_roomData_codec);
      testData_.WriteTo(output, _map_testData_codec);
      xiaoyaoPaijiuCardGroupData_.WriteTo(output, _map_xiaoyaoPaijiuCardGroupData_codec);
      xiaoyaoPaijiuCardGroupScoreData_.WriteTo(output, _map_xiaoyaoPaijiuCardGroupScoreData_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += crazyPaijiuCardGroupData_.CalculateSize(_map_crazyPaijiuCardGroupData_codec);
      size += crazyPaijiuCardGroupScoreData_.CalculateSize(_map_crazyPaijiuCardGroupScoreData_codec);
      size += laotiePaijiuCardGroupData_.CalculateSize(_map_laotiePaijiuCardGroupData_codec);
      size += laotiePaijiuCardGroupScoreData_.CalculateSize(_map_laotiePaijiuCardGroupScoreData_codec);
      size += paijiuCardData_.CalculateSize(_map_paijiuCardData_codec);
      size += paijiuCardGroupData_.CalculateSize(_map_paijiuCardGroupData_codec);
      size += paijiuCardGroupScoreData_.CalculateSize(_map_paijiuCardGroupScoreData_codec);
      size += roomData_.CalculateSize(_map_roomData_codec);
      size += testData_.CalculateSize(_map_testData_codec);
      size += xiaoyaoPaijiuCardGroupData_.CalculateSize(_map_xiaoyaoPaijiuCardGroupData_codec);
      size += xiaoyaoPaijiuCardGroupScoreData_.CalculateSize(_map_xiaoyaoPaijiuCardGroupScoreData_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DataManager other) {
      if (other == null) {
        return;
      }
      crazyPaijiuCardGroupData_.Add(other.crazyPaijiuCardGroupData_);
      crazyPaijiuCardGroupScoreData_.Add(other.crazyPaijiuCardGroupScoreData_);
      laotiePaijiuCardGroupData_.Add(other.laotiePaijiuCardGroupData_);
      laotiePaijiuCardGroupScoreData_.Add(other.laotiePaijiuCardGroupScoreData_);
      paijiuCardData_.Add(other.paijiuCardData_);
      paijiuCardGroupData_.Add(other.paijiuCardGroupData_);
      paijiuCardGroupScoreData_.Add(other.paijiuCardGroupScoreData_);
      roomData_.Add(other.roomData_);
      testData_.Add(other.testData_);
      xiaoyaoPaijiuCardGroupData_.Add(other.xiaoyaoPaijiuCardGroupData_);
      xiaoyaoPaijiuCardGroupScoreData_.Add(other.xiaoyaoPaijiuCardGroupScoreData_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            crazyPaijiuCardGroupData_.AddEntriesFrom(input, _map_crazyPaijiuCardGroupData_codec);
            break;
          }
          case 18: {
            crazyPaijiuCardGroupScoreData_.AddEntriesFrom(input, _map_crazyPaijiuCardGroupScoreData_codec);
            break;
          }
          case 26: {
            laotiePaijiuCardGroupData_.AddEntriesFrom(input, _map_laotiePaijiuCardGroupData_codec);
            break;
          }
          case 34: {
            laotiePaijiuCardGroupScoreData_.AddEntriesFrom(input, _map_laotiePaijiuCardGroupScoreData_codec);
            break;
          }
          case 42: {
            paijiuCardData_.AddEntriesFrom(input, _map_paijiuCardData_codec);
            break;
          }
          case 50: {
            paijiuCardGroupData_.AddEntriesFrom(input, _map_paijiuCardGroupData_codec);
            break;
          }
          case 58: {
            paijiuCardGroupScoreData_.AddEntriesFrom(input, _map_paijiuCardGroupScoreData_codec);
            break;
          }
          case 66: {
            roomData_.AddEntriesFrom(input, _map_roomData_codec);
            break;
          }
          case 74: {
            testData_.AddEntriesFrom(input, _map_testData_codec);
            break;
          }
          case 82: {
            xiaoyaoPaijiuCardGroupData_.AddEntriesFrom(input, _map_xiaoyaoPaijiuCardGroupData_codec);
            break;
          }
          case 90: {
            xiaoyaoPaijiuCardGroupScoreData_.AddEntriesFrom(input, _map_xiaoyaoPaijiuCardGroupScoreData_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class CrazyPaijiuCardGroupData : pb::IMessage<CrazyPaijiuCardGroupData> {
    private static readonly pb::MessageParser<CrazyPaijiuCardGroupData> _parser = new pb::MessageParser<CrazyPaijiuCardGroupData>(() => new CrazyPaijiuCardGroupData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CrazyPaijiuCardGroupData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::com.bsl.data.StaticDataProtoReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CrazyPaijiuCardGroupData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CrazyPaijiuCardGroupData(CrazyPaijiuCardGroupData other) : this() {
      id_ = other.id_;
      name_ = other.name_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CrazyPaijiuCardGroupData Clone() {
      return new CrazyPaijiuCardGroupData(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CrazyPaijiuCardGroupData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CrazyPaijiuCardGroupData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Name != other.Name) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CrazyPaijiuCardGroupData other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class CrazyPaijiuCardGroupScoreData : pb::IMessage<CrazyPaijiuCardGroupScoreData> {
    private static readonly pb::MessageParser<CrazyPaijiuCardGroupScoreData> _parser = new pb::MessageParser<CrazyPaijiuCardGroupScoreData>(() => new CrazyPaijiuCardGroupScoreData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CrazyPaijiuCardGroupScoreData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::com.bsl.data.StaticDataProtoReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CrazyPaijiuCardGroupScoreData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CrazyPaijiuCardGroupScoreData(CrazyPaijiuCardGroupScoreData other) : this() {
      id_ = other.id_;
      score_ = other.score_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CrazyPaijiuCardGroupScoreData Clone() {
      return new CrazyPaijiuCardGroupScoreData(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "score" field.</summary>
    public const int ScoreFieldNumber = 2;
    private int score_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Score {
      get { return score_; }
      set {
        score_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CrazyPaijiuCardGroupScoreData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CrazyPaijiuCardGroupScoreData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Score != other.Score) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Score != 0) hash ^= Score.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Score != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Score);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Score != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Score);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CrazyPaijiuCardGroupScoreData other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Score != 0) {
        Score = other.Score;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 16: {
            Score = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class LaotiePaijiuCardGroupData : pb::IMessage<LaotiePaijiuCardGroupData> {
    private static readonly pb::MessageParser<LaotiePaijiuCardGroupData> _parser = new pb::MessageParser<LaotiePaijiuCardGroupData>(() => new LaotiePaijiuCardGroupData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LaotiePaijiuCardGroupData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::com.bsl.data.StaticDataProtoReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LaotiePaijiuCardGroupData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LaotiePaijiuCardGroupData(LaotiePaijiuCardGroupData other) : this() {
      id_ = other.id_;
      name_ = other.name_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LaotiePaijiuCardGroupData Clone() {
      return new LaotiePaijiuCardGroupData(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LaotiePaijiuCardGroupData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LaotiePaijiuCardGroupData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Name != other.Name) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LaotiePaijiuCardGroupData other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class LaotiePaijiuCardGroupScoreData : pb::IMessage<LaotiePaijiuCardGroupScoreData> {
    private static readonly pb::MessageParser<LaotiePaijiuCardGroupScoreData> _parser = new pb::MessageParser<LaotiePaijiuCardGroupScoreData>(() => new LaotiePaijiuCardGroupScoreData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LaotiePaijiuCardGroupScoreData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::com.bsl.data.StaticDataProtoReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LaotiePaijiuCardGroupScoreData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LaotiePaijiuCardGroupScoreData(LaotiePaijiuCardGroupScoreData other) : this() {
      id_ = other.id_;
      score_ = other.score_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LaotiePaijiuCardGroupScoreData Clone() {
      return new LaotiePaijiuCardGroupScoreData(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "score" field.</summary>
    public const int ScoreFieldNumber = 2;
    private int score_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Score {
      get { return score_; }
      set {
        score_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LaotiePaijiuCardGroupScoreData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LaotiePaijiuCardGroupScoreData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Score != other.Score) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Score != 0) hash ^= Score.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Score != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Score);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Score != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Score);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LaotiePaijiuCardGroupScoreData other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Score != 0) {
        Score = other.Score;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 16: {
            Score = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class PaijiuCardData : pb::IMessage<PaijiuCardData> {
    private static readonly pb::MessageParser<PaijiuCardData> _parser = new pb::MessageParser<PaijiuCardData>(() => new PaijiuCardData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PaijiuCardData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::com.bsl.data.StaticDataProtoReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PaijiuCardData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PaijiuCardData(PaijiuCardData other) : this() {
      id_ = other.id_;
      card_ = other.card_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PaijiuCardData Clone() {
      return new PaijiuCardData(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "card" field.</summary>
    public const int CardFieldNumber = 2;
    private int card_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Card {
      get { return card_; }
      set {
        card_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PaijiuCardData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PaijiuCardData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Card != other.Card) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Card != 0) hash ^= Card.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Card != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Card);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Card != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Card);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PaijiuCardData other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Card != 0) {
        Card = other.Card;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Card = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class PaijiuCardGroupData : pb::IMessage<PaijiuCardGroupData> {
    private static readonly pb::MessageParser<PaijiuCardGroupData> _parser = new pb::MessageParser<PaijiuCardGroupData>(() => new PaijiuCardGroupData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PaijiuCardGroupData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::com.bsl.data.StaticDataProtoReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PaijiuCardGroupData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PaijiuCardGroupData(PaijiuCardGroupData other) : this() {
      id_ = other.id_;
      name_ = other.name_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PaijiuCardGroupData Clone() {
      return new PaijiuCardGroupData(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PaijiuCardGroupData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PaijiuCardGroupData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Name != other.Name) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PaijiuCardGroupData other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class PaijiuCardGroupScoreData : pb::IMessage<PaijiuCardGroupScoreData> {
    private static readonly pb::MessageParser<PaijiuCardGroupScoreData> _parser = new pb::MessageParser<PaijiuCardGroupScoreData>(() => new PaijiuCardGroupScoreData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PaijiuCardGroupScoreData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::com.bsl.data.StaticDataProtoReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PaijiuCardGroupScoreData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PaijiuCardGroupScoreData(PaijiuCardGroupScoreData other) : this() {
      id_ = other.id_;
      score_ = other.score_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PaijiuCardGroupScoreData Clone() {
      return new PaijiuCardGroupScoreData(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "score" field.</summary>
    public const int ScoreFieldNumber = 2;
    private int score_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Score {
      get { return score_; }
      set {
        score_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PaijiuCardGroupScoreData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PaijiuCardGroupScoreData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Score != other.Score) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Score != 0) hash ^= Score.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Score != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Score);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Score != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Score);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PaijiuCardGroupScoreData other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Score != 0) {
        Score = other.Score;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 16: {
            Score = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class RoomData : pb::IMessage<RoomData> {
    private static readonly pb::MessageParser<RoomData> _parser = new pb::MessageParser<RoomData>(() => new RoomData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RoomData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::com.bsl.data.StaticDataProtoReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RoomData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RoomData(RoomData other) : this() {
      id_ = other.id_;
      money_ = other.money_.Clone();
      maxBet_ = other.maxBet_;
      eachMoney_ = other.eachMoney_.Clone();
      isAddGold_ = other.isAddGold_;
      isWinner2Dizhu_ = other.isWinner2Dizhu_;
      paijiuDataName_ = other.paijiuDataName_;
      enterGold_ = other.enterGold_.Clone();
      outGold_ = other.outGold_.Clone();
      rebate_ = other.rebate_;
      instanceName_ = other.instanceName_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RoomData Clone() {
      return new RoomData(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "money" field.</summary>
    public const int MoneyFieldNumber = 2;
    private static readonly pbc::MapField<int, int>.Codec _map_money_codec
        = new pbc::MapField<int, int>.Codec(pb::FieldCodec.ForInt32(8), pb::FieldCodec.ForInt32(16), 18);
    private readonly pbc::MapField<int, int> money_ = new pbc::MapField<int, int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, int> Money {
      get { return money_; }
    }

    /// <summary>Field number for the "maxBet" field.</summary>
    public const int MaxBetFieldNumber = 3;
    private double maxBet_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double MaxBet {
      get { return maxBet_; }
      set {
        maxBet_ = value;
      }
    }

    /// <summary>Field number for the "eachMoney" field.</summary>
    public const int EachMoneyFieldNumber = 4;
    private static readonly pbc::MapField<int, int>.Codec _map_eachMoney_codec
        = new pbc::MapField<int, int>.Codec(pb::FieldCodec.ForInt32(8), pb::FieldCodec.ForInt32(16), 34);
    private readonly pbc::MapField<int, int> eachMoney_ = new pbc::MapField<int, int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, int> EachMoney {
      get { return eachMoney_; }
    }

    /// <summary>Field number for the "isAddGold" field.</summary>
    public const int IsAddGoldFieldNumber = 5;
    private int isAddGold_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int IsAddGold {
      get { return isAddGold_; }
      set {
        isAddGold_ = value;
      }
    }

    /// <summary>Field number for the "isWinner2Dizhu" field.</summary>
    public const int IsWinner2DizhuFieldNumber = 6;
    private int isWinner2Dizhu_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int IsWinner2Dizhu {
      get { return isWinner2Dizhu_; }
      set {
        isWinner2Dizhu_ = value;
      }
    }

    /// <summary>Field number for the "paijiuDataName" field.</summary>
    public const int PaijiuDataNameFieldNumber = 7;
    private string paijiuDataName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PaijiuDataName {
      get { return paijiuDataName_; }
      set {
        paijiuDataName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "enterGold" field.</summary>
    public const int EnterGoldFieldNumber = 8;
    private static readonly pbc::MapField<int, int>.Codec _map_enterGold_codec
        = new pbc::MapField<int, int>.Codec(pb::FieldCodec.ForInt32(8), pb::FieldCodec.ForInt32(16), 66);
    private readonly pbc::MapField<int, int> enterGold_ = new pbc::MapField<int, int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, int> EnterGold {
      get { return enterGold_; }
    }

    /// <summary>Field number for the "outGold" field.</summary>
    public const int OutGoldFieldNumber = 9;
    private static readonly pbc::MapField<int, int>.Codec _map_outGold_codec
        = new pbc::MapField<int, int>.Codec(pb::FieldCodec.ForInt32(8), pb::FieldCodec.ForInt32(16), 74);
    private readonly pbc::MapField<int, int> outGold_ = new pbc::MapField<int, int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, int> OutGold {
      get { return outGold_; }
    }

    /// <summary>Field number for the "rebate" field.</summary>
    public const int RebateFieldNumber = 10;
    private int rebate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Rebate {
      get { return rebate_; }
      set {
        rebate_ = value;
      }
    }

    /// <summary>Field number for the "instanceName" field.</summary>
    public const int InstanceNameFieldNumber = 11;
    private string instanceName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string InstanceName {
      get { return instanceName_; }
      set {
        instanceName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RoomData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RoomData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!Money.Equals(other.Money)) return false;
      if (MaxBet != other.MaxBet) return false;
      if (!EachMoney.Equals(other.EachMoney)) return false;
      if (IsAddGold != other.IsAddGold) return false;
      if (IsWinner2Dizhu != other.IsWinner2Dizhu) return false;
      if (PaijiuDataName != other.PaijiuDataName) return false;
      if (!EnterGold.Equals(other.EnterGold)) return false;
      if (!OutGold.Equals(other.OutGold)) return false;
      if (Rebate != other.Rebate) return false;
      if (InstanceName != other.InstanceName) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      hash ^= Money.GetHashCode();
      if (MaxBet != 0D) hash ^= MaxBet.GetHashCode();
      hash ^= EachMoney.GetHashCode();
      if (IsAddGold != 0) hash ^= IsAddGold.GetHashCode();
      if (IsWinner2Dizhu != 0) hash ^= IsWinner2Dizhu.GetHashCode();
      if (PaijiuDataName.Length != 0) hash ^= PaijiuDataName.GetHashCode();
      hash ^= EnterGold.GetHashCode();
      hash ^= OutGold.GetHashCode();
      if (Rebate != 0) hash ^= Rebate.GetHashCode();
      if (InstanceName.Length != 0) hash ^= InstanceName.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      money_.WriteTo(output, _map_money_codec);
      if (MaxBet != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(MaxBet);
      }
      eachMoney_.WriteTo(output, _map_eachMoney_codec);
      if (IsAddGold != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(IsAddGold);
      }
      if (IsWinner2Dizhu != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(IsWinner2Dizhu);
      }
      if (PaijiuDataName.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(PaijiuDataName);
      }
      enterGold_.WriteTo(output, _map_enterGold_codec);
      outGold_.WriteTo(output, _map_outGold_codec);
      if (Rebate != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(Rebate);
      }
      if (InstanceName.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(InstanceName);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      size += money_.CalculateSize(_map_money_codec);
      if (MaxBet != 0D) {
        size += 1 + 8;
      }
      size += eachMoney_.CalculateSize(_map_eachMoney_codec);
      if (IsAddGold != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IsAddGold);
      }
      if (IsWinner2Dizhu != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IsWinner2Dizhu);
      }
      if (PaijiuDataName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PaijiuDataName);
      }
      size += enterGold_.CalculateSize(_map_enterGold_codec);
      size += outGold_.CalculateSize(_map_outGold_codec);
      if (Rebate != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Rebate);
      }
      if (InstanceName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(InstanceName);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RoomData other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      money_.Add(other.money_);
      if (other.MaxBet != 0D) {
        MaxBet = other.MaxBet;
      }
      eachMoney_.Add(other.eachMoney_);
      if (other.IsAddGold != 0) {
        IsAddGold = other.IsAddGold;
      }
      if (other.IsWinner2Dizhu != 0) {
        IsWinner2Dizhu = other.IsWinner2Dizhu;
      }
      if (other.PaijiuDataName.Length != 0) {
        PaijiuDataName = other.PaijiuDataName;
      }
      enterGold_.Add(other.enterGold_);
      outGold_.Add(other.outGold_);
      if (other.Rebate != 0) {
        Rebate = other.Rebate;
      }
      if (other.InstanceName.Length != 0) {
        InstanceName = other.InstanceName;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            money_.AddEntriesFrom(input, _map_money_codec);
            break;
          }
          case 25: {
            MaxBet = input.ReadDouble();
            break;
          }
          case 34: {
            eachMoney_.AddEntriesFrom(input, _map_eachMoney_codec);
            break;
          }
          case 40: {
            IsAddGold = input.ReadInt32();
            break;
          }
          case 48: {
            IsWinner2Dizhu = input.ReadInt32();
            break;
          }
          case 58: {
            PaijiuDataName = input.ReadString();
            break;
          }
          case 66: {
            enterGold_.AddEntriesFrom(input, _map_enterGold_codec);
            break;
          }
          case 74: {
            outGold_.AddEntriesFrom(input, _map_outGold_codec);
            break;
          }
          case 80: {
            Rebate = input.ReadInt32();
            break;
          }
          case 90: {
            InstanceName = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class TestData : pb::IMessage<TestData> {
    private static readonly pb::MessageParser<TestData> _parser = new pb::MessageParser<TestData>(() => new TestData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TestData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::com.bsl.data.StaticDataProtoReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TestData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TestData(TestData other) : this() {
      id_ = other.id_;
      name_ = other.name_;
      age_ = other.age_;
      exp_ = other.exp_.Clone();
      weapon_ = other.weapon_.Clone();
      testLong_ = other.testLong_;
      testDouble_ = other.testDouble_;
      testListDouble_ = other.testListDouble_.Clone();
      testMapDouble_ = other.testMapDouble_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TestData Clone() {
      return new TestData(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "age" field.</summary>
    public const int AgeFieldNumber = 3;
    private int age_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Age {
      get { return age_; }
      set {
        age_ = value;
      }
    }

    /// <summary>Field number for the "exp" field.</summary>
    public const int ExpFieldNumber = 4;
    private static readonly pb::FieldCodec<int> _repeated_exp_codec
        = pb::FieldCodec.ForInt32(34);
    private readonly pbc::RepeatedField<int> exp_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> Exp {
      get { return exp_; }
    }

    /// <summary>Field number for the "weapon" field.</summary>
    public const int WeaponFieldNumber = 5;
    private static readonly pbc::MapField<int, string>.Codec _map_weapon_codec
        = new pbc::MapField<int, string>.Codec(pb::FieldCodec.ForInt32(8), pb::FieldCodec.ForString(18), 42);
    private readonly pbc::MapField<int, string> weapon_ = new pbc::MapField<int, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, string> Weapon {
      get { return weapon_; }
    }

    /// <summary>Field number for the "testLong" field.</summary>
    public const int TestLongFieldNumber = 6;
    private long testLong_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long TestLong {
      get { return testLong_; }
      set {
        testLong_ = value;
      }
    }

    /// <summary>Field number for the "testDouble" field.</summary>
    public const int TestDoubleFieldNumber = 7;
    private double testDouble_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double TestDouble {
      get { return testDouble_; }
      set {
        testDouble_ = value;
      }
    }

    /// <summary>Field number for the "testListDouble" field.</summary>
    public const int TestListDoubleFieldNumber = 8;
    private static readonly pb::FieldCodec<double> _repeated_testListDouble_codec
        = pb::FieldCodec.ForDouble(66);
    private readonly pbc::RepeatedField<double> testListDouble_ = new pbc::RepeatedField<double>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<double> TestListDouble {
      get { return testListDouble_; }
    }

    /// <summary>Field number for the "testMapDouble" field.</summary>
    public const int TestMapDoubleFieldNumber = 9;
    private static readonly pbc::MapField<long, double>.Codec _map_testMapDouble_codec
        = new pbc::MapField<long, double>.Codec(pb::FieldCodec.ForInt64(8), pb::FieldCodec.ForDouble(17), 74);
    private readonly pbc::MapField<long, double> testMapDouble_ = new pbc::MapField<long, double>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<long, double> TestMapDouble {
      get { return testMapDouble_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TestData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TestData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Name != other.Name) return false;
      if (Age != other.Age) return false;
      if(!exp_.Equals(other.exp_)) return false;
      if (!Weapon.Equals(other.Weapon)) return false;
      if (TestLong != other.TestLong) return false;
      if (TestDouble != other.TestDouble) return false;
      if(!testListDouble_.Equals(other.testListDouble_)) return false;
      if (!TestMapDouble.Equals(other.TestMapDouble)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Age != 0) hash ^= Age.GetHashCode();
      hash ^= exp_.GetHashCode();
      hash ^= Weapon.GetHashCode();
      if (TestLong != 0L) hash ^= TestLong.GetHashCode();
      if (TestDouble != 0D) hash ^= TestDouble.GetHashCode();
      hash ^= testListDouble_.GetHashCode();
      hash ^= TestMapDouble.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Age != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Age);
      }
      exp_.WriteTo(output, _repeated_exp_codec);
      weapon_.WriteTo(output, _map_weapon_codec);
      if (TestLong != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(TestLong);
      }
      if (TestDouble != 0D) {
        output.WriteRawTag(57);
        output.WriteDouble(TestDouble);
      }
      testListDouble_.WriteTo(output, _repeated_testListDouble_codec);
      testMapDouble_.WriteTo(output, _map_testMapDouble_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Age != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Age);
      }
      size += exp_.CalculateSize(_repeated_exp_codec);
      size += weapon_.CalculateSize(_map_weapon_codec);
      if (TestLong != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TestLong);
      }
      if (TestDouble != 0D) {
        size += 1 + 8;
      }
      size += testListDouble_.CalculateSize(_repeated_testListDouble_codec);
      size += testMapDouble_.CalculateSize(_map_testMapDouble_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TestData other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Age != 0) {
        Age = other.Age;
      }
      exp_.Add(other.exp_);
      weapon_.Add(other.weapon_);
      if (other.TestLong != 0L) {
        TestLong = other.TestLong;
      }
      if (other.TestDouble != 0D) {
        TestDouble = other.TestDouble;
      }
      testListDouble_.Add(other.testListDouble_);
      testMapDouble_.Add(other.testMapDouble_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            Age = input.ReadInt32();
            break;
          }
          case 34:
          case 32: {
            exp_.AddEntriesFrom(input, _repeated_exp_codec);
            break;
          }
          case 42: {
            weapon_.AddEntriesFrom(input, _map_weapon_codec);
            break;
          }
          case 48: {
            TestLong = input.ReadInt64();
            break;
          }
          case 57: {
            TestDouble = input.ReadDouble();
            break;
          }
          case 66:
          case 65: {
            testListDouble_.AddEntriesFrom(input, _repeated_testListDouble_codec);
            break;
          }
          case 74: {
            testMapDouble_.AddEntriesFrom(input, _map_testMapDouble_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class XiaoyaoPaijiuCardGroupData : pb::IMessage<XiaoyaoPaijiuCardGroupData> {
    private static readonly pb::MessageParser<XiaoyaoPaijiuCardGroupData> _parser = new pb::MessageParser<XiaoyaoPaijiuCardGroupData>(() => new XiaoyaoPaijiuCardGroupData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<XiaoyaoPaijiuCardGroupData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::com.bsl.data.StaticDataProtoReflection.Descriptor.MessageTypes[10]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public XiaoyaoPaijiuCardGroupData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public XiaoyaoPaijiuCardGroupData(XiaoyaoPaijiuCardGroupData other) : this() {
      id_ = other.id_;
      name_ = other.name_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public XiaoyaoPaijiuCardGroupData Clone() {
      return new XiaoyaoPaijiuCardGroupData(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as XiaoyaoPaijiuCardGroupData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(XiaoyaoPaijiuCardGroupData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Name != other.Name) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(XiaoyaoPaijiuCardGroupData other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class XiaoyaoPaijiuCardGroupScoreData : pb::IMessage<XiaoyaoPaijiuCardGroupScoreData> {
    private static readonly pb::MessageParser<XiaoyaoPaijiuCardGroupScoreData> _parser = new pb::MessageParser<XiaoyaoPaijiuCardGroupScoreData>(() => new XiaoyaoPaijiuCardGroupScoreData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<XiaoyaoPaijiuCardGroupScoreData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::com.bsl.data.StaticDataProtoReflection.Descriptor.MessageTypes[11]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public XiaoyaoPaijiuCardGroupScoreData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public XiaoyaoPaijiuCardGroupScoreData(XiaoyaoPaijiuCardGroupScoreData other) : this() {
      id_ = other.id_;
      score_ = other.score_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public XiaoyaoPaijiuCardGroupScoreData Clone() {
      return new XiaoyaoPaijiuCardGroupScoreData(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "score" field.</summary>
    public const int ScoreFieldNumber = 2;
    private int score_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Score {
      get { return score_; }
      set {
        score_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as XiaoyaoPaijiuCardGroupScoreData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(XiaoyaoPaijiuCardGroupScoreData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Score != other.Score) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Score != 0) hash ^= Score.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Score != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Score);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Score != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Score);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(XiaoyaoPaijiuCardGroupScoreData other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Score != 0) {
        Score = other.Score;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 16: {
            Score = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
